config/routes.rb
Rails.application.routes.draw do
  resources :trains
  resources :railway_stations
  get 'wellcome/index'
  root 'wellcome#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/railway_station.rb
class RailwayStation < ApplicationRecord
end

app/models/train.rb
class Train < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/railway_stations_controller.rb
class RailwayStationsController < ApplicationController
  before_action :set_railway_station, only: %i[ show edit update destroy ]

  # GET /railway_stations or /railway_stations.json
  def index
    @railway_stations = RailwayStation.all
  end

  # GET /railway_stations/1 or /railway_stations/1.json
  def show
  end

  # GET /railway_stations/new
  def new
    @railway_station = RailwayStation.new
  end

  # GET /railway_stations/1/edit
  def edit
  end

  # POST /railway_stations or /railway_stations.json
  def create
    @railway_station = RailwayStation.new(railway_station_params)

    respond_to do |format|
      if @railway_station.save
        format.html { redirect_to railway_station_url(@railway_station), notice: "Railway station was successfully created." }
        format.json { render :show, status: :created, location: @railway_station }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /railway_stations/1 or /railway_stations/1.json
  def update
    respond_to do |format|
      if @railway_station.update(railway_station_params)
        format.html { redirect_to railway_station_url(@railway_station), notice: "Railway station was successfully updated." }
        format.json { render :show, status: :ok, location: @railway_station }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @railway_station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /railway_stations/1 or /railway_stations/1.json
  def destroy
    @railway_station.destroy

    respond_to do |format|
      format.html { redirect_to railway_stations_url, notice: "Railway station was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_railway_station
      @railway_station = RailwayStation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def railway_station_params
      params.require(:railway_station).permit(:title)
    end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[ show edit update destroy ]

  # GET /trains or /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1 or /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains or /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to train_url(@train), notice: "Train was successfully created." }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1 or /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to train_url(@train), notice: "Train was successfully updated." }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1 or /trains/1.json
  def destroy
    @train.destroy

    respond_to do |format|
      format.html { redirect_to trains_url, notice: "Train was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_train
      @train = Train.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def train_params
      params.require(:train).permit(:number)
    end
end

app/controllers/wellcome_controller.rb
class WellcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/railway_stations_helper.rb
module RailwayStationsHelper
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/helpers/wellcome_helper.rb
module WellcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railway</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/railway_stations/_form.html.erb
<%= form_with(model: railway_station) do |form| %>
  <% if railway_station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(railway_station.errors.count, "error") %> prohibited this railway_station from being saved:</h2>

      <ul>
        <% railway_station.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/railway_stations/edit.html.erb
<h1>Editing Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Show', @railway_station %> |
<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Railway Stations</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @railway_stations.each do |railway_station| %>
      <tr>
        <td><%= railway_station.title %></td>
        <td><%= link_to 'Show', railway_station %></td>
        <td><%= link_to 'Edit', edit_railway_station_path(railway_station) %></td>
        <td><%= link_to 'Destroy', railway_station, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Railway Station', new_railway_station_path %>

app/views/railway_stations/new.html.erb
<h1>New Railway Station</h1>

<%= render 'form', railway_station: @railway_station %>

<%= link_to 'Back', railway_stations_path %>

app/views/railway_stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @railway_station.title %>
</p>

<%= link_to 'Edit', edit_railway_station_path(@railway_station) %> |
<%= link_to 'Back', railway_stations_path %>

app/views/trains/_form.html.erb
<%= form_with(model: train) do |form| %>
  <% if train.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(train.errors.count, "error") %> prohibited this train from being saved:</h2>

      <ul>
        <% train.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
    <tr>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @trains.each do |train| %>
      <tr>
        <td><%= train.number %></td>
        <td><%= link_to 'Show', train %></td>
        <td><%= link_to 'Edit', edit_train_path(train) %></td>
        <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number:</strong>
  <%= @train.number %>
</p>

<%= link_to 'Edit', edit_train_path(@train) %> |
<%= link_to 'Back', trains_path %>

app/views/wellcome/index.html.erb
<h1>Привіт, це Денис!</h1>

<%= link_to "Список станцій", railway_stations_path %>
<%= link_to "Список потягів", trains_path %>